version: '3.9'

services:
  api:
    image: node:alpine
    container_name: api_nodejs
    command: 'npm start'
    env_file:
      - .env
    working_dir: /usr/src/app
    ports:
      - 3333:3000
    volumes:
      - ./api:/usr/src/app
